### ISSUE TITLE
Movement/goToPosture is "slow" (in Linux initially, but after that also in Windows)

### ISSUE THREAD

**Issue by ceefour** [lumenrobot/avatar-nao#3]
Probably because we need `waitUntilMoveIsFinished()`.

But strangely, sometimes this isn't needed, so there's probably a flag/setting somewhere.

**Comment by ceefour** [comment]
In Windows it's working now with `waitUntilMoveIsFinished`, but not in Linux :(

it's as if speed = 0.07 instead of 0.7.

**Comment by ceefour** [comment]
Even this on Linux is still slow:

```
posture.goToPosture("Stand", 0.95f)
```

But speed 1.0f <del>works</del> sometimes, sometimes not working.

**Comment by ceefour** [comment]
My conclusion is: on Linux, _any_ goToPosture call with speed < 1f will activate "slow mode".

In order to restore it, you must:
- motion.killAll()
- motion.rest()
- wait a few minutes
- now try again, making sure you always call goToPosture with speed 1f

**Comment by ceefour** [comment]
Based on this error I know exactly what's wrong:

```
java.lang.RuntimeException:     ALMotion::SOAP error:   ALBroker::methodCall: method: setAngles, params: [["RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw", "RHand"], [-0, -0, 0, 0, -0, 1], 0]
                ALMotion::setAngles
                ALMotion::setAngles
        fractionMaxSpeed: Expected a fraction of max speed between 0.0 and 1.0
        SOAP detail: ALMotion
        at com.aldebaran.proxy.jnaoqiJNI.ALProxy_call__SWIG_3(Native Method) ~[jnaoqi-1.14.5.jar:na]
        at com.aldebaran.proxy.ALProxy.call(ALProxy.java:55) ~[jnaoqi-1.14.5.jar:na]
        at com.aldebaran.proxy.ALMotionProxy.setAngles(ALMotionProxy.java:1097) ~[jnaoqi-1.14.5.jar:na]
        at org.lskk.lumen.avatar.nao.ActingRouter.lambda$configure$10(ActingRouter.java:52) ~[classes/:na]
```

the Java code is this:

```
    motion.setAngles(
            new Variant(new String[]{"RShoulderPitch", "RShoulderRoll", "RElbowYaw", "RElbowRoll", "RWristYaw", "RHand"}),
            new Variant(new float[]{-0.9f, -0.44f, 0.53f, 0.3f, -0.2f, 1.0f}), 0.5f);
```

So basically, in Linux(64) jnaoqi is broken, any `float` value is turned into int, making 0.5 into 0 and only 1.0f becomes 1. This is true not just speed, but **any** float value, for example angles above.
Making jnaoqi on Linux(64) practically unusable. :(
